name: GitHub Issue to Hexo
author: 'JasonZeng <zenghongtu@gmail.com>'
description: GitHub Action which converts GitHub Issue to Hexo post
branding:
  icon: arrow-up-circle
  color: gray-dark
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
    
  milestone:
    description: 'Filter issues by milestone for Hexo. Default `publish`'
    required: false
    default: 'publish'
  output:
    description: 'The directory of the hexo source. Default `./`'
    required: false
    default: './'

runs:
  using: node16
  main: dist/index.js